let p = Number(prompt("Mời bạn nhập điểm môn Vật lý: "));
let c = Number(prompt("Mời bạn nhập điểm môn Hóa học: "));
let b = Number(prompt("Mời bạn nhập điểm môn Sinh học: "));
let sum = p + c + b;
let con = (p+c+b)/3;
console.log("Tổng điểm 3 môn: ");
sum;
console.log(sum);
console.log("Điểm trung bình: ");
con;
console.log(con);