let width = Number(prompt("Mời bạn nhập vào chiều rộng hcn"));
let height = Number(prompt("Mời bạn nhập vào chiều dài hcn"));
let x = width*height;
let c = (width+height)/2;
console.log("Chu vi hcn là: ");
c;
console.log(c);
console.log("Diện tích hcn là: ");
x;
console.log(x);
